{{- if .Values.storage }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.className }}
provisioner: {{ .Values.storage.provisioner }}
mountOptions:
  - tls
{{- end }}