name: Test Get Charts

on:
  push:

jobs:
  get-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm linting
        working-directory: charts
        run: |
          for d in */ ; do
              echo "Running on directory $d"
              helm lint $d -f $d/values.yaml.Example 
          done